# Generated by Django 4.1.2 on 2022-10-12 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addresses',
        ),
    ]
